# Generated by Django 6.0.6 on 2026-06-14 20:02

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productcollection'),
    ]

    operations = [
        TrigramExtension(),
    ]
