# Generated by Django 6.0.6 on 2026-06-18 18:45

import django.db.models.deletion
from django.db import migrations, models

def link_user_profiles(apps, schema_editor):
    Address = apps.get_model('shop', 'Address')
    UserProfile = apps.get_model('shop', 'UserProfile')
    for address in Address.objects.all():
        profile = UserProfile.objects.filter(user_id=address.user_id).first()
        if profile:
            address.user_profile = profile
            address.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_address_options_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_profile',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresses',
                to='shop.userprofile'
            ),
        ),
        migrations.RunPython(link_user_profiles),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='user_profile',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='addresses',
                to='shop.userprofile'
            ),
        ),
    ]
