# Generated by Django 5.0.6 on 2026-06-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_stocknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('ninja', '🥷'), ('alien', '👽'), ('robot', '🤖'), ('ghost', '👻'), ('wizard', '🧙'), ('astronaut', '🧑\u200d🚀'), ('cat', '😺')], default='ninja', max_length=20),
        ),
    ]
