# Generated by Django 5.0.6 on 2026-06-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_refundrequest_refundtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('support', 'Support'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
