# Generated by Django 5.0.6 on 2026-07-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_taskexecutionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('languages', models.CharField(default='English, Hindi, Spanish, French', help_text='Comma-separated list of languages', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('current_language_index', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('recipient_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='SENT', max_length=50)),
                ('exception', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shop.aiemailcampaign')),
            ],
        ),
    ]
