# Generated by Django 5.0.6 on 2026-07-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_aiemailcampaign_aiemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemailcampaign',
            name='schedule_unit',
            field=models.CharField(default='Minutes', help_text='Interval unit (Minutes, Hours, Days, Weeks)', max_length=20),
        ),
        migrations.AddField(
            model_name='aiemailcampaign',
            name='schedule_value',
            field=models.IntegerField(default=1, help_text='Interval value'),
        ),
    ]
