# Generated by Django 5.0.6 on 2026-07-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_coupon_cart_created_at_cart_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='Order ID or Cart ID', max_length=100)),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('RESERVED', 'Reserved'), ('COMMITTED', 'Committed'), ('RELEASED', 'Released'), ('RESTOCKED', 'Restocked')], max_length=20)),
                ('idempotency_key', models.CharField(help_text='Ensures idempotent operations', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
